#!/usr/bin/env python3
"""Generate light-on-dark monochrome UI icons from navy source SVGs.

Reads:  hopper-presentation-rest/.../static/images/*.svg
Writes: .../static/images/dark/<same-name>.svg

Skips multi-color logos. Run after adding a new monochrome toolbar/list icon:

  python3 scripts/generate-dark-icons.py

Commit the generated files under images/dark/.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "hopper-presentation-rest/src/main/resources/WEB-INF/static/images"
OUT = SRC / "dark"

# Multi-color / brand art — do not auto-invert
SKIP = {
    "hopper-presentation-logo.svg",
    "hopper-presentation.svg",
}

# Target ink for dark chrome (matches --hopper-text)
DARK_INK = "#e8eef9"

# Common navy / dark fills used in source icons
FILL_RE = re.compile(
    r"(fill\s*[:=]\s*[\"']?)(#0[eE]3[aA]5[aA]|#0[eE]3[aA]|#123|#234|#000000|#000|#111|#222|"
    r"#0f172a|#1e293b|#334155|#0b1220|rgb\s*\(\s*14\s*,\s*58\s*,\s*90\s*\))",
    re.IGNORECASE,
)
STYLE_FILL_RE = re.compile(
    r"(fill\s*:\s*)(#0[eE]3[aA]5[aA]|#0[eE]3[aA]|#123|#234|#000000|#000|#111|#222|"
    r"#0f172a|#1e293b|#334155|#0b1220|rgb\s*\(\s*14\s*,\s*58\s*,\s*90\s*\))",
    re.IGNORECASE,
)
STROKE_RE = re.compile(
    r"(stroke\s*[:=]\s*[\"']?)(#0[eE]3[aA]5[aA]|#0[eE]3[aA]|#123|#234|#000000|#000|#111|#222)",
    re.IGNORECASE,
)


def transform(svg: str) -> str:
    # style="fill:#0e3a5a;..."
    svg = STYLE_FILL_RE.sub(rf"\1{DARK_INK}", svg)
    svg = FILL_RE.sub(rf"\1{DARK_INK}", svg)
    svg = STROKE_RE.sub(rf"\1{DARK_INK}", svg)
    # bare fill="#0e3a5a" already covered; currentColor → keep
    return svg


def main() -> int:
    if not SRC.is_dir():
        print(f"Source dir not found: {SRC}", file=sys.stderr)
        return 1
    OUT.mkdir(parents=True, exist_ok=True)
    n = 0
    for path in sorted(SRC.glob("*.svg")):
        if path.name in SKIP:
            print(f"skip {path.name}")
            continue
        text = path.read_text(encoding="utf-8")
        out_text = transform(text)
        if out_text == text:
            # Still write a copy (may already use currentColor or only black that we missed)
            # Try forcing any remaining hex fills that look dark (low luminance approx)
            out_text = re.sub(
                r'fill="(#[0-9a-fA-F]{3,8})"',
                lambda m: f'fill="{DARK_INK}"'
                if m.group(1).lower() not in ("#fff", "#ffffff", "#e8eef9", "none")
                and m.group(1).lower() != "none"
                else m.group(0),
                out_text,
            )
            out_text = re.sub(
                r"fill:\s*(#[0-9a-fA-F]{3,8})",
                lambda m: f"fill:{DARK_INK}"
                if m.group(1).lower() not in ("#fff", "#ffffff", "#e8eef9")
                else m.group(0),
                out_text,
            )
        dest = OUT / path.name
        header = (
            f"<!-- Generated by scripts/generate-dark-icons.py from ../{path.name} — do not edit by hand -->\n"
        )
        if not out_text.lstrip().startswith("<!-- Generated"):
            # insert after xml decl if present
            if out_text.startswith("<?xml"):
                nl = out_text.find("\n")
                out_text = out_text[: nl + 1] + header + out_text[nl + 1 :]
            else:
                out_text = header + out_text
        dest.write_text(out_text, encoding="utf-8")
        n += 1
        print(f"wrote {dest.relative_to(ROOT)}")
    print(f"Done: {n} dark icons in {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
